apiVersion: v1
kind: Service
metadata:
  name: polr-mysql
  labels:
    app: polr
  namespace: polr
spec:
  ports:
    - port: 3306
  selector:
    app: polr
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polr-mysql
  labels:
    app: polr
  namespace: polr
spec:
  selector:
    matchLabels:
      app: polr
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: polr
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polr-env
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: polr-env
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: polr-env
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polr-env
              key: DB_PASSWORD

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: polr-mysql-storage
          mountPath: /var/lib/mysql/
      volumes:
      - name: polr-mysql-storage
        persistentVolumeClaim:
          claimName: polr-mysql-pv-claim

