apiVersion: v1
kind: Secret
metadata:
  name: polr-env
  namespace: polr
type: Opaque
data:
  POLR_SETUP_RAN: dHJ1ZQ==
  APP_PROTOCOL: aHR0cDovLw==
  APP_ADDRESS: ZXhhbXBsZS5jb20=
  DB_HOST: cG9sci1teXNxbA==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  DB_DATABASE: cG9scg==
  DB_USERNAME: cG9scg==
  DB_PASSWORD: cG9scg==
  APP_NAME: UG9scg==
  SETTING_PUBLIC_INTERFACE: ZmFsc2U=
  SETTING_ANON_API: ZmFsc2U=
  SETTING_SHORTEN_PERMISSION: dHJ1ZQ==
  QUEUE_DRIVER: ZGF0YWJhc2U=
  SETTING_PSEUDORANDOM_ENDING: dHJ1ZQ==
  _PSEUDO_RANDOM_KEY_LENGTH: NQ==
  APP_KEY: T0dydUpNSmpoaWI3MGRuUVpPME9CUU1oQk1KRTFsMEQ=
