
apiVersion: v1

kind: Secret
metadata:
  name: users-sql
  namespace: polr
type: Opaque
data:
  users.sql: SU5TRVJUIElHTk9SRSBJTlRPIHVzZXJzIFZBTFVFUyAoMSwnYWRtaW4nLCckMnkkMTAkUXF4NE9ycFZPN2Q1VlRHREZmUnJrdTJodzNxUEdETHhWZHZzL0UyanEwZ1JCbzAyN1dzWEMnLCdhZG1pbkBhZG1pbi50bGQnLCcxNzIuMTkuMC4xJywnY2ZjOWJiMzllNGVjZjI1MjhjOTAwODMzMDE3MGI4MjZmODRlOWFmOTZlZDkzMjg4NjNjNmY1OTMxZjM3ZDY2MDY3ZjcxMDYxNzUxNmE1YjdmMDNiNDRhZGUwNTM4YzM4MGFhMycsJ2FkbWluJywnMScsJzAnLDAsJzYwJywnMjAxOC0wNy0wOSAxMTo0Njo1OCcsJzIwMTgtMDctMDkgMTE6NDY6NTgnLE5VTEwpOwo=
